#!/bin/bash

# --- 1. LOAD SECRETS ------------------------------------------
SECRET_FILE="/root/.backup_secrets.env"

if [ -f "$SECRET_FILE" ]; then
    source "$SECRET_FILE"
else
    echo "🚨 Error: Secret file not found at $SECRET_FILE"
    exit 1
fi

# --- 2. CONFIGURATION -----------------------------------------
# Paths
BACKUP_ROOT="/opt/backup-staging"          # Temporary staging area
SURE_BACKUPS="/opt/sure-data/backups/last" # Where Sure auto-dumps to
N8N_DATA_VOL="n8n_data"                    # Docker volume name for n8n files

# Timestamps
TODAY=$(date +"%Y-%m-%d")
NOW=$(date +"%H-%M-%S")
TEMP_DIR="$BACKUP_ROOT/$TODAY/$NOW"
RCLONE_DEST="$REMOTE_NAME:$BUCKET_NAME"

# --- 3. PREPARATION -------------------------------------------
mkdir -p "$TEMP_DIR"
echo "[$(date)] 🚀 Starting Unified Backup..."

# --- 4. BACKUP N8N STACK --------------------------------------
echo "[$(date)] 📸 Snapshotting n8n..."

# A. Dump n8n Database (solar_db)
# Uses the password from your .env file
docker exec -e PGPASSWORD="$SOLAR_DB_PASSWORD" solar_db pg_dumpall -U "$SOLAR_DB_USER" -c > "$TEMP_DIR/n8n_solar_db.sql"

# B. Backup n8n Configs/Keys (The .n8n folder)
# Mounts the volume to a temp alpine container to zip it safely
docker run --rm -v "$N8N_DATA_VOL":/source -v "$TEMP_DIR":/backup alpine tar -czf /backup/n8n_files_archive.tar.gz -C /source .

# --- 5. BACKUP SURE STACK -------------------------------------
echo "[$(date)] 📦 Collecting Sure Backups..."

# Grab the latest dump generated by your existing sure_backup container
if [ -d "$SURE_BACKUPS" ]; then
    cp -r "$SURE_BACKUPS"/* "$TEMP_DIR/"
else
    echo "⚠️ Warning: Sure backup folder not found at $SURE_BACKUPS. Check sure_backup container."
fi

# --- 6. COMPRESSION & ENCRYPTION ------------------------------
echo "[$(date)] 🔒 Encrypting Archive..."

# 1. Tar the specific timestamp folder
tar -cf "$BACKUP_ROOT/full_backup_$TODAY.tar" -C "$BACKUP_ROOT/$TODAY" "$NOW"

# 2. Encrypt using the password from .env
# We pipe the password into GPG to avoid interactive prompts
echo "$BACKUP_ENCRYPTION_PASS" | gpg --batch --yes --passphrase-fd 0 --symmetric --cipher-algo AES256 -o "$BACKUP_ROOT/full_backup_$TODAY.tar.gpg" "$BACKUP_ROOT/full_backup_$TODAY.tar"

# --- 7. UPLOAD TO CLOUD (OFFSITE) -----------------------------
echo "[$(date)] ☁️ Uploading to R2..."

rclone copy "$BACKUP_ROOT/full_backup_$TODAY.tar.gpg" "$RCLONE_DEST/$TODAY"

if [ $? -eq 0 ]; then
  echo "[$(date)] ✅ Upload Successful."
else
  echo "[$(date)] ❌ Upload Failed!"
fi

# --- 8. CLEANUP -----------------------------------------------
echo "[$(date)] 🧹 Cleaning up..."
rm -rf "$BACKUP_ROOT/$TODAY"
rm "$BACKUP_ROOT/full_backup_$TODAY.tar"
rm "$BACKUP_ROOT/full_backup_$TODAY.tar.gpg"

echo "[$(date)] 🏁 Backup Complete!"